ClubHouse App
Jhonatanssal/Authentication-RoR pull request #1
Opened 2020-09-30 16:27 UTC by jssarrazolaa

### This PR has:

- Create a user authentication with gem devise
- Create models Users and Post
- Connect User to their corresponding Post
- Add logic to let only Signed in user see Author of the posts

Happy coding. :+1:

2020-09-30 18:05 UTC, tirthajyoti-ghosh requested changes
# ⚠️  Invalid

Please add a descriptive README to your project to make it professional.

I am marking this project invalid. Please request another code review when you are done.

2020-09-30 22:48 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
##### UsersController

##### `new` action

* [x] it has a `new` action with `User.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

##### `create` action

* [x] it has a create action. Must use `user_params` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))

- [x] Check comments below

## [OPTIONAL ]
- [x] Lets add validation to models.

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +        format.json { render :show, status: :created, location: @post }
Lets remove JSON render as we are not building APIs

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +        format.json { render json: @post.errors, status: :unprocessable_entity }
Lets remove JSON render as we are not building APIs

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +        format.json { render json: @post.errors, status: :unprocessable_entity }
Lets remove JSON render as we are not building APIs

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_user!, except: %i[index show]
- [ ] it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2020-09-30 22:48 UTC, kobiyoyo commented on app/views/posts/index.html.erb
> +          <% end %>
- [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)

2020-09-30 22:48 UTC, kobiyoyo commented on app/views/posts/index.html.erb
> +          <% end %>
View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)

2020-09-30 22:48 UTC, kobiyoyo commented on app/views/posts/show.html.erb
> +      <% end %>
View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +    set_post
You can set a before_ action to handle this.in case of any ambiguity don't hesitate to contact me.

2020-09-30 22:48 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +    set_post
You can set a before_ action to handle this.

2020-10-01 18:29 UTC, christianotieno requested changes
# Changes Required ♻️ 
Good job team, we have done a splendid job with the reviews. Keep it up. 👏 

Let's work one small bug that got introduced while working on the changes below before we proceed. Thanks 👇 

### Happy coding 💻 
#### Christian Otieno (TSE)

2020-10-01 18:36 UTC, christianotieno requested changes

2020-10-01 18:36 UTC, christianotieno commented on app/models/post.rb
> +  validates :tittle, :body, presence: true
# Mend the bug brought about by the validation.
- [ ] A user is unable to create a post successfully as the validation confuses rails. Let's fix this.
![Screenshot 2020-10-01 213325](https://user-images.githubusercontent.com/22345961/94849388-02634900-042e-11eb-8a24-a2169e2415ba.png)
```suggestion
  validates :title, :body, presence: true
```

2020-10-01 22:54 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-10-01 23:01 UTC, merged